eureka:
  client:
     healthcheck:
       enabled: true
     serviceUrl:
        defaultZone: http://localhost:${server.port}/eu/eureka  
  instance:
    hostname: localhost
    preferIpAddress: true           
