eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
     healthcheck:
       enabled: true
     serviceUrl:
        defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/.well-known/jwks.json
  kafka: 
    bootstrapServers: localhost:9092   
        
